spring.application.name=ricettario

# collegamento db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ricettario?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# Mostra query in console
# udate solo in sviluppo al primo avvio crea tabelle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Abilita i metodi delete update con hidden input
spring.mvc.hiddenmethod.filter.enabled=true

# Start data sql not at first alunch when creating db
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#Percorso storage
app.upload.dir=/var/www/uploads/recipes