name: Build Spring Boot JAR

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Configura Java 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Permessi wrapper Maven (se presente)
      run: test -f ./mvnw && chmod +x ./mvnw || true

    - name: Compila e genera il JAR
      run: mvn clean package -DskipTests

    - name: Salva il JAR come Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar