name: Build Spring Boot JAR

on:
  push:
    branches: [ "main", "master" ] # Viene eseguito ad ogni push su questi branch
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Configura Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compila e genera il JAR
      run: mvn clean package -DskipTests

    - name: Salva il JAR come Artifact (Scaricabile da GitHub)
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar